### PR TITLE
pre-release: `v2.11.0-beta.1`

### PR DESCRIPTION
**Pull request by rustatian**
# Reason for This PR

- pre-release cycle.

## 👀 New:

- ✏️ **[BETA]: RoadRunner**: Can now be embedded in other go programs. [PR](https://github.com/roadrunner-server/roadrunner/pull/1214), (thanks @khepin)
- ✏️ **gRPC Plugin**: Implement Google's `gRPC` [errors API](https://cloud.google.com/apis/design/errors). An exception might be passed as a `Status` structure in the `Metadata` (key - `error`) to be parsed and returned to the user w/o worker restart. NOTE: `Status` structure should be marshaled via `proto` marshaller, not `json`. [FR](https://github.com/roadrunner-server/roadrunner/issues/1001)
- ✏️ **gRPC Plugin**: `gRPC` reflection server. Docs: https://roadrunner.dev/docs/app-server-grpc/2.x/en, [GoDocs](https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md).
- ✏️ **Logger Plugin**: Get rid of the `context deadline exceeded` error on worker's allocation. We updated the error message with the link to the docs with the most common causes for the `worker allocation failed` error: https://roadrunner.dev/docs/known-issues-allocate-timeout/2.x/en. Feel free to add your cases here :)

The reflection server might be activated to use [`grpc_cli`](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md), [`grpc-curl`](https://github.com/fullstorydev/grpcurl), [`grpc-ui`](https://github.com/fullstorydev/grpcui), or similar tools to intercept grpc payloads.

Configuration:
```yaml
grpc:
  listen: "tcp://localhost:9001"

  # GRPC reflection server [SINCE 2.11]
  #
  # This option is optional. The reflection server might be activated to use `grpc_cli`, `grpc-ui`, `grpc-curl`, or similar tools to intercept grpc payloads.
  enable_reflection_server: false
  proto:
    - "first.proto"
    - "second.proto"
```

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by khepin** [comment]
Been able to integrate this into our embedded apps with no problem. 👍

**Comment by rustatian** [comment]
Brilliant, thanks 👍🏻 
One small note, please, use the `-race` flag to build your app (at least for testing). I suspect that there might be race conditions.

**Comment by khepin** [comment]
Not too familiar with that flag, but building our app with `build -race ...` builds with no issues

**Comment by rustatian** [comment]
> Not too familiar with that flag, but building our app with `build -race ...` builds with no issues

Np, you may have a look at this article: https://go.dev/doc/articles/race_detector

You need to build and run your app to be sure that there are no data races. It will work slower than usual during the testing.

**Comment by khepin** [comment]
Was able to build and run with `-race` and test the code paths we've implemented. Not getting any data race report so all looks good.

**Pull request merged**
