### PR TITLE
feature: add `envfile` support

### PR DESCRIPTION
**Pull request by shellphy**
# Reason for This PR

It is easier to configure environment variables in the.env file, Reduce the maintenance of configuration files

## Description of Changes

It is implemented by variable substitution at the entry. 

add .env file:

```
APP_ENV=production
LOG_LEVEL=warning
```

add variable in rr.yml:

```
envfile: .env
logs:
  mode: ${APP_ENV:-developement}
  level: ${LOG_LEVEL:-debug}
``` 

run `rr serve -c rr.yml`, then a temp config file will be used by rr :

```
envfile: .env
logs:
  mode: production
  level: warning
```

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

## Summary by CodeRabbit

- **New Features**
	- Enhanced configuration management by introducing dynamic processing of configuration files and environment variables.
	- Added functionality to expand environment variables within configuration inputs.
	- Improved server initialization process with better handling of YAML configuration files and optional environment files.
	- Introduced error handling for configuration processing to ensure robust command execution.

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @shellphy 👋 
Thank you for the PR 👍 
However, RR already supports envfiles: [link](https://github.com/roadrunner-server/roadrunner/blob/master/internal/cli/root.go#L156).

**Comment by shellphy** [comment]
I see that you support envfiles, but there are very few environment variables supported now, and it is not used to replace the configuration in rr.yml, my implementation is a more general scheme, can be more flexible, I think it is necessary, otherwise I need to maintain multiple rr.yml configuration files

**Comment by rustatian** [comment]
All envs are supported and used to replace placeholders, see configuration (config) plugin. Your implementation has several critical errors:
1. Writing tmp config (why?) under some predefined permissions. Configuration might contain sensitive info.
2. You don't need to use regex to parse envs.

**Comment by rustatian** [comment]
3. You don't need to maintain multiply .rr.yaml configurations. Just use includes.

**Pull request closed without merging**
