### PR TITLE
chore: make `StartWatchdog` channel read only, graceful debug server stopping

### PR DESCRIPTION
**Pull request by GhostWalkers**
# Reason for This PR

`
because I can :)
`

## Description of Changes

`
a small typed change, and the server debug process is completed only after all remaining requests have been fully processed
`

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by rustatian** [comment]
@GhostWalkers Hey 👋🏻 
Thanks for the PR, seems to be a reasonable improvement 👍🏻

**Review by rustatian — APPROVED** [review]
LGTM

**Comment by rustatian** [comment]
@GhostWalkers I slightly improved the error handling mechanism when starting the debug (pprof) server.

**Comment by GhostWalkers** [comment]
@rustatian This looks great!

**Pull request merged**
