### PR TITLE
feature: Introducing RoadRunner Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [RoadRunner Guru](https://gurubase.io/g/roadrunner) to Gurubase. RoadRunner Guru uses the data from this repo and data from the [docs](https://docs.roadrunner.dev/docs) to answer questions by leveraging the LLM.

In this PR, I showcased the "RoadRunner Guru", which highlights that RoadRunner now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable RoadRunner Guru in Gurubase, just let me know that's totally fine.

## Summary by CodeRabbit

- **New Features**
	- Added a badge linking to Gurubase for enhanced resource visibility.
	- Introduced a new link to "Ask RoadRunner Guru" in the footer for additional support.

- **Documentation**
	- Updated the README.md to improve user engagement and support resources.

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @kursataktas 👋 Nice to meet you. Yeah, sure, why not 😃

**Comment by kursataktas** [comment]
Hi @rustatian,

I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by rustatian** [comment]
Hey @kursataktas 👋🏻 
Sure, would be really cool if you keep updating this thread 👍🏻 Thank you.

I checked the details, we use `GitBook` to host our docs, so it'd be really nice to have a simple tutorial on how to add `Gurubase` on such docs sites.

**Comment by kursataktas** [comment]
Great to hear that 🎊 

GitBook will be a tough one since, as far as I know, they don’t allow users to add custom scripts. However, I’ll look into it and update this thread if I find a way.

**Comment by kursataktas** [comment]
Hello @rustatian,

I want to share an exciting update about Gurubase. We've recently released several great features that I think you'll find interesting.

### 1. Slack & Discord Integration
You can now add your Guru as a bot to Slack and Discord, allowing you to ask questions instantly. More details here: [Discord Bot Integration](https://docs.gurubase.ai/integrations/discord-bot).

### 2. Analytics Dashboard
Track what your users ask your Guru and gain valuable insights. This feature is available on the "My Gurus" page. If you haven’t maintained your Guru yet, I highly recommend doing so to access your analytics. More information about claiming your Guru can be found [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).
image

### 3. API Support
All Guru functionalities are now accessible via API. You can ask questions, edit data sources, and more using our API endpoints. Here is the [API Doc](https://docs.gurubase.ai/api-reference/introduction).

### 4. Codebase Indexing
We now support indexing codebases from GitHub repositories to generate answers for related queries. This feature is available for select Gurus. If you don’t see the "Codebase Indexed" label on your Guru edit page and would like access, please let me know, I’d be happy to enable it for you!
image

Let me know if you have any questions or feedback!

**Comment by rustatian** [comment]
Very cool, thanks @kursataktas 👍🏻

**Comment by kursataktas** [comment]
Hey @rustatian,

I have two updates for you. 

First, we now have native GitBook integration. You can install the Gurubase widget via the GitBook marketplace. You can find more details [here](https://docs.gurubase.ai/integrations/website-widget#gitbook).

The second update is that we’ve released the Gurubase GitHub bot!
This means you can now integrate your Guru into your repository,  so users can ask it questions directly through GitHub issues. By default, the Gurubase bot automatically responds to newly opened issues, but you can customize its behavior if needed.

You can see it in action in [this demo issue](https://github.com/Gurubase/gurubase/issues/248).
More information about the bot can be found [here](https://docs.gurubase.ai/integrations/github-bot).

gurubase-github-bot-demo

-----

_Note: As I mentioned in my first update on this thread, please let me know if you’d prefer not to receive updates here._

**Comment by rustatian** [comment]
Hey @kursataktas 👋🏻 
Cool updates 👍🏻 
I sent a request to create a Guru (Widget ID) to add to our docs via GitBook.

**Comment by kursataktas** [comment]
Hey @rustatian 

I saw your request, but since RoadRunner Guru is already available, I just bound it to your Guru account so you can manage it. You can find it on the 'My Gurus' page.

**Comment by rustatian** [comment]
image
Done @kursataktas 👍🏻

**Pull request merged**
